 #bhushan
### Run Query to insert DaTA INTO TABLE
# INSERT INTO "THEME_MODULE" ("USERID_THEME_OPT", "THEME_TYPE", "MODEL_1","MODEL_2", "MODEL_3", "MODEL_4","MODEL_5", "MODEL_6", "MODEL_7","MODEL_8", "MODEL_9", "MODEL_10")
# VALUES ('000001', 'MARS', 'ARCHIVAL','RETRIVAL','SEARCH','MODEL_4','MODEL_5','MODEL_6','MODEL_7','MODEL_8','MODEL_9','MODEL_10');


# INSERT INTO "THEME_MODULE" ("USERID_THEME_OPT", "THEME_TYPE", "MODEL_1","MODEL_2", "MODEL_3", "MODEL_4","MODEL_5", "MODEL_6", "MODEL_7","MODEL_8", "MODEL_9", "MODEL_10")
# VALUES ('000002', 'AGRICULTURE', 'NDVI','STACK','CLASSIFICATION','MODEL_4','MODEL_5','MODEL_6','MODEL_7','MODEL_8','MODEL_9','MODEL_10'),
# 		('000003', 'WATER', 'NDWI','FLOOD','DROUGH','MODEL_4','MODEL_5','MODEL_6','MODEL_7','MODEL_8','MODEL_9','MODEL_10'),
# 		('000004', 'MINING', 'SITE_MONITORING','ILLEGAL_MINING_DETECTION','STOCKPILE_MONITORING','MODEL_4','MODEL_5','MODEL_6','MODEL_7','MODEL_8','MODEL_9','MODEL_10'),
# 		('000005', 'DEFENCE', 'MILITARY_STRATEGIC_PLANNING','SPACE_TRAFFIC_MANAGEMENT','PLANETARY_EXPLORATION','MODEL_4','MODEL_5','MODEL_6','MODEL_7','MODEL_8','MODEL_9','MODEL_10'); 
