import React, { useState, useEffect, useRef, createContext, useContext } from "react";
import "./TableContents.css"; // Import the CSS file

// import { BlobReader, BlobWriter, ZipReader, ZipWriter } from '@zip.js/zip.js';
// import axios from 'axios';
import GeopicxTables from '../../GeopicxTables/GeopicxTables';

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faCloud,
    faXmark,
} from "@fortawesome/free-solid-svg-icons";
import Dropdown from 'react-bootstrap/Dropdown';
import { useMap } from "../../UseContext/MapContext"; // Adjust the import path as needed

import SelectByAttribute from '../../../asset/SVG_Icons_64/TASelect_By_Attribute64.svg'
import FindAndReplace from '../../../asset/SVG_Icons_64/TAFindAndReplace64.svg'
import SwitchSelection from '../../../asset/SVG_Icons_64/TA_Switch_Selection64.svg'
import ClearSelection from '../../../asset/SVG_Icons_64/TAClear_Selection64.svg'
import SelectAll from '../../../asset/SVG_Icons_64/TASelectAll64.svg'
import AddFields from '../../../asset/SVG_Icons_64/TAAddFields64.svg'
import ViewFields from '../../../asset/SVG_Icons_64/TAViewFields64.svg'
import TurnAllFieldsON from '../../../asset/SVG_Icons_64/TATurnAllFieldsOn_64.svg'
import ShowFieldsAliases from '../../../asset/SVG_Icons_64/TAShowFieldAliases_64.svg'
import CalculateFields from '../../../asset/SVG_Icons_64/TACalculateFields64.svg'
// import RestoreFieldorder from '../../../asset/SVG_Icons_64/TAR'
import HorizontalTabGroup from '../../../asset/SVG_Icons_64/TAHoriTabGroup64.svg'
import VerticalTabGroup from '../../../asset/SVG_Icons_64/TAVerticalTabGroup64.svg'
import JoinTable from '../../../asset/SVG_Icons_64/TAJoinTable64.svg'
import Removejoin from '../../../asset/SVG_Icons_64/TARemoveJoin64.svg'
import Relate from '../../../asset/SVG_Icons_64/TARelateTable64.svg'
import RemoveRelate from '../../../asset/SVG_Icons_64/TARemoveRelate64.svg'
import JoinandRelate from '../../../asset/SVG_Icons_64/TAJoinAndRelate_64.svg'
import ArrangeTables from '../../../asset/SVG_Icons_64/TAArrangeTable64.svg'
import Export from '../../../asset/SVG_Icons_64/TAExportTable64.svg'
import RelatedTables from '../../../asset/SVG_Icons_64/TARelateTable64.svg'



const TableContentsComp = ({ sent_datav, TableLinevalues, TablePointvalues , updatedataTable }) => {

    // console.log("Tabledatdatdataaa: ", SentTableData);
    console.log("TableLinevalues: ", TableLinevalues);
    console.log("TablePointvalues: ", TablePointvalues);
    const { mapRef, fileLayersMap } = useMap(); // Access context values

    // Function to retrieve layers for a specific file
    const getFileLayers = (fileName) => {
        if (fileLayersMap?.current?.has(fileName)) {
            if (fileLayersMap.current.get(fileName).lineProperties) {
                return fileLayersMap.current.get(fileName).lineProperties;
            } else {
                return fileLayersMap.current.get(fileName).pointProperties;
            }
        } else {
            console.warn(`No layers found for file: ${fileName}`);
            return null;
        }
    };



    const transformToTable = (dataArray) => {
        if (!Array.isArray(dataArray) || dataArray.length === 0) {
            console.warn("Invalid dataArray provided for transformation");
            return null;
        }

        // Add a unique `id` and stringify keys and values
        const dataWithIds = dataArray.map((item, index) => {
            const stringifiedItem = {};
            for (const key in item) {
                const stringKey = String(key); // Ensure the key is a string
                stringifiedItem[stringKey] = String(item[key]); // Ensure the value is a string
            }
            return {
                id: String(index + 1), // Add `id` as a string
                ...stringifiedItem,    // Add the transformed properties
            };
        });

        // Extract column headers
        const columns = Object.keys(dataWithIds[0]).map((key) => ({
            header: key,          //.toUpperCase(), // Use uppercase for the header
            accessor: key,            // Use the key as the accessor
        }));

        return {
            name: "Generated Table", // You can name the table dynamically if needed
            columns,
            data: dataWithIds,
        };
    };



    // Retrieve the data for transformation
    const fileLayersData = getFileLayers(updatedataTable?.updatedataTable);

    // Transform the data into table format
    let tablesss = [];
    if (fileLayersData) {
        const transformedTable = transformToTable(fileLayersData);
        if (transformedTable) {
            tablesss = [transformedTable];
        }
        console.log("tablesss", tablesss);
    }

    // Submenu visibility state and toggle function
    const [visibleSubmenus, setVisibleSubmenus] = useState({});

    const toggleSubmenu = (submenu, isVisible) => {
        setVisibleSubmenus((prev) => ({
            ...prev,
            [submenu]: isVisible,
        }));
    };

    // const tablesss = [
    //     {
    //         "name": "Table 1",
    //         "columns": [
    //             { "header": "id", "accessor": "id" },
    //             { "header": "DATACODE", "accessor": "DATACODE" },
    //             { "header": "DATANAME", "accessor": "DATANAME" },
                
    //         ],
    //         "data": [
    //             {
    //                 "id": 1,
    //                 "DATACODE": "AB823728",
    //                 "DATANAME": "DS_PHR1B_201903230537361_FR1_PX_E077N12_1123_01156",
    //             },
                
    //             {
    //                 "id": 2,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //             },
    //             {
    //                 "id": 3,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //             },
    //             {
    //                 "id": 4,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //             },
                
                
    //         ]
    //     },
    //     {
    //         "name": "Table 2",
    //         "columns": [
    //             { "header": "id", "accessor": "id" },
    //             { "header": "DATACODE", "accessor": "DATACODE" },
    //             { "header": "DATANAME", "accessor": "DATANAME" },
    //             { "header": "COMP_NA", "accessor": "COMP_NA" },
    //             { "header": "SATT_NA", "accessor": "SATT_NA" },
    //             { "header": "CL_REF", "accessor": "CL_REF" },
    //             { "header": "CL_ORDNA", "accessor": "CL_ORDNA" },
    //             { "header": "CL_PROJNA", "accessor": "CL_PROJNA" },
    //             { "header": "CL_PURPOSE", "accessor": "CL_PURPOSE" },
    //             { "header": "CL_ADDRESS1", "accessor": "CL_ADDRESS1" },
    //             { "header": "CL_ADDRESS2", "accessor": "CL_ADDRESS2" },
    //             { "header": "SEN_NAME", "accessor": "SEN_NAME" },
    //             { "header": "IMG_DATYPE", "accessor": "IMG_DATYPE" },
    //             { "header": "IMG_DAPROC", "accessor": "IMG_DAPROC" },
    //             { "header": "IMG_DATE", "accessor": "IMG_DATE" },
    //             { "header": "IMG_DT_RNG", "accessor": "IMG_DT_RNG" },
    //             { "header": "DLOCA_CY", "accessor": "DLOCA_CY" },
    //             { "header": "DLOCA_ST", "accessor": "DLOCA_ST" },
    //             { "header": "DLOCA_DT", "accessor": "DLOCA_DT" },
    //             { "header": "DLOCA_LOCA", "accessor": "DLOCA_LOCA" },
    //             { "header": "DAREA", "accessor": "DAREA" },
    //             { "header": "DSIZE", "accessor": "DSIZE" },
    //             { "header": "DQLNAME", "accessor": "DQLNAME" },
    //             { "header": "DFORMAT", "accessor": "DFORMAT" },
    //             { "header": "DCLOUD", "accessor": "DCLOUD" },
    //             { "header": "DSNOW", "accessor": "DSNOW" },
    //             { "header": "D_AQ_BITS", "accessor": "D_AQ_BITS" },
    //             { "header": "D_PR_BITS", "accessor": "D_PR_BITS" },
    //             { "header": "DPRJ_TABLE", "accessor": "DPRJ_TABLE" },
    //             { "header": "DPRJ_NAME", "accessor": "DPRJ_NAME" },
    //             { "header": "D_NROWS", "accessor": "D_NROWS" },
    //             { "header": "D_NCOLS", "accessor": "D_NCOLS" },
    //             { "header": "D_NBANDS", "accessor": "D_NBANDS" },
    //             { "header": "D_NTILES", "accessor": "D_NTILES" },
    //             { "header": "D_TYPE", "accessor": "D_TYPE" },
    //             { "header": "D_NBITS", "accessor": "D_NBITS" },
    //             { "header": "D_SIGN", "accessor": "D_SIGN" },
    //             { "header": "D_IN_ANGL", "accessor": "D_IN_ANGL" },
    //             { "header": "D_GSD_AXT", "accessor": "D_GSD_AXT" },
    //             { "header": "D_GSD_ALT", "accessor": "D_GSD_ALT" },
    //             { "header": "D_PIXELX", "accessor": "D_PIXELX" },
    //             { "header": "D_PIXELY", "accessor": "D_PIXELY" },
    //             { "header": "AL_DA_PATH", "accessor": "AL_DA_PATH" },
    //             { "header": "AL_SH_PATH", "accessor": "AL_SH_PATH" },
    //             { "header": "AL_QL_PATH", "accessor": "AL_QL_PATH" },
    //             { "header": "XML_FILE", "accessor": "XML_FILE" }
    //         ],
    //         "data": [
    //             {
    //                 "id": 1,
    //                 "DATACODE": "AB823728",
    //                 "DATANAME": "DS_PHR1B_201903230537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008910",
    //                 "CL_ORDNA": "gfg",
    //                 "CL_PROJNA": "gdg",
    //                 "CL_PURPOSE": "fgdg",
    //                 "CL_ADDRESS1": "dgg",
    //                 "CL_ADDRESS2": "dfgg",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "23-03-2019",
    //                 "IMG_DT_RNG": "ggf",
    //                 "DLOCA_CY": "dgd",
    //                 "DLOCA_ST": "dfdg",
    //                 "DLOCA_DT": "dfgg",
    //                 "DLOCA_LOCA": "fg",
    //                 "DAREA": "69.5517",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_201903230538130_ORT_3917261101.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "0",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29372",
    //                 "D_NCOLS": "15407",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "26.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "dfgdg",
    //                 "AL_SH_PATH": "dg",
    //                 "AL_QL_PATH": "fgdg",
    //                 "XML_FILE": "DIM_PHR1B_PMS_201903230538130_ORT_3917261101.XML"
    //             },
    //             {
    //                 "id": 2,
    //                 "DATACODE": "AB340502",
    //                 "DATANAME": "PNEO3_202308040551179_PMS-FS_ORT",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PNEO",
    //                 "CL_REF": "A9-AOI",
    //                 "CL_ORDNA": "sadad",
    //                 "CL_PROJNA": "adasd",
    //                 "CL_PURPOSE": "adad",
    //                 "CL_ADDRESS1": "asdasd",
    //                 "CL_ADDRESS2": "asdasd",
    //                 "SEN_NAME": "PNEO 3",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS-FS",
    //                 "IMG_DATE": "04-08-2023",
    //                 "IMG_DT_RNG": "asdad",
    //                 "DLOCA_CY": "sdad",
    //                 "DLOCA_ST": "adad",
    //                 "DLOCA_DT": "asda",
    //                 "DLOCA_LOCA": "sdad",
    //                 "DAREA": "103.8210153",
    //                 "DSIZE": "8.8 GB",
    //                 "DQLNAME": "PREVIEW_PNEO3_202308040551179_PMS-FS_ORT_PWOI_000116673_1_2_F_1.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "64.74064722",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "16",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32644",
    //                 "D_NROWS": "34608",
    //                 "D_NCOLS": "34776",
    //                 "D_NBANDS": "6",
    //                 "D_NTILES": "4",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "31.67836468",
    //                 "D_GSD_AXT": "0.40711993",
    //                 "D_GSD_ALT": "0.343409747",
    //                 "D_PIXELX": "0.3",
    //                 "D_PIXELY": "0.3",
    //                 "AL_DA_PATH": "adad",
    //                 "AL_SH_PATH": "ads",
    //                 "AL_QL_PATH": "adsad",
    //                 "XML_FILE": "DIM_PNEO3_PMS-FS_202308040551179_ORTHO_PWOI_000116673_1_2_F_1.XML"
    //             },
    //             {
    //                 "id": 3,
    //                 "DATACODE": "AB123456",
    //                 "DATANAME": "DS_PHR1B_202106250537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008911",
    //                 "CL_ORDNA": "xyz",
    //                 "CL_PROJNA": "xyz",
    //                 "CL_PURPOSE": "xyz",
    //                 "CL_ADDRESS1": "abc",
    //                 "CL_ADDRESS2": "def",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "25-06-2021",
    //                 "IMG_DT_RNG": "xyz",
    //                 "DLOCA_CY": "xyz",
    //                 "DLOCA_ST": "xyz",
    //                 "DLOCA_DT": "xyz",
    //                 "DLOCA_LOCA": "xyz",
    //                 "DAREA": "50.1234",
    //                 "DSIZE": "1.2 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106250537361_ORT_3917261102.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "5",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29000",
    //                 "D_NCOLS": "15000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "25.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path1",
    //                 "AL_SH_PATH": "path2",
    //                 "AL_QL_PATH": "path3",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106250537361_ORT_3917261102.XML"
    //             },
    //             {
    //                 "id": 4,
    //                 "DATACODE": "AB654321",
    //                 "DATANAME": "DS_PHR1B_202106260537361_FR1_PX_E077N12_1123_01157",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008912",
    //                 "CL_ORDNA": "uvw",
    //                 "CL_PROJNA": "uvw",
    //                 "CL_PURPOSE": "uvw",
    //                 "CL_ADDRESS1": "ghi",
    //                 "CL_ADDRESS2": "jkl",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "26-06-2021",
    //                 "IMG_DT_RNG": "uvw",
    //                 "DLOCA_CY": "uvw",
    //                 "DLOCA_ST": "uvw",
    //                 "DLOCA_DT": "uvw",
    //                 "DLOCA_LOCA": "uvw",
    //                 "DAREA": "55.1234",
    //                 "DSIZE": "1.3 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106260537361_ORT_3917261103.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "6",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29500",
    //                 "D_NCOLS": "15200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "24.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path4",
    //                 "AL_SH_PATH": "path5",
    //                 "AL_QL_PATH": "path6",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106260537361_ORT_3917261103.XML"
    //             },
    //             {
    //                 "id": 5,
    //                 "DATACODE": "AB765432",
    //                 "DATANAME": "DS_PHR1B_202106270537361_FR1_PX_E077N12_1123_01158",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008913",
    //                 "CL_ORDNA": "rst",
    //                 "CL_PROJNA": "rst",
    //                 "CL_PURPOSE": "rst",
    //                 "CL_ADDRESS1": "mno",
    //                 "CL_ADDRESS2": "pqr",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "27-06-2021",
    //                 "IMG_DT_RNG": "rst",
    //                 "DLOCA_CY": "rst",
    //                 "DLOCA_ST": "rst",
    //                 "DLOCA_DT": "rst",
    //                 "DLOCA_LOCA": "rst",
    //                 "DAREA": "60.1234",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106270537361_ORT_3917261104.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "7",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30000",
    //                 "D_NCOLS": "15400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "23.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path7",
    //                 "AL_SH_PATH": "path8",
    //                 "AL_QL_PATH": "path9",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106270537361_ORT_3917261104.XML"
    //             },
    //             {
    //                 "id": 6,
    //                 "DATACODE": "AB987654",
    //                 "DATANAME": "DS_PHR1B_202106280537361_FR1_PX_E077N12_1123_01159",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008914",
    //                 "CL_ORDNA": "opq",
    //                 "CL_PROJNA": "opq",
    //                 "CL_PURPOSE": "opq",
    //                 "CL_ADDRESS1": "stu",
    //                 "CL_ADDRESS2": "vwx",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "28-06-2021",
    //                 "IMG_DT_RNG": "opq",
    //                 "DLOCA_CY": "opq",
    //                 "DLOCA_ST": "opq",
    //                 "DLOCA_DT": "opq",
    //                 "DLOCA_LOCA": "opq",
    //                 "DAREA": "65.1234",
    //                 "DSIZE": "1.5 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106280537361_ORT_3917261105.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "8",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30500",
    //                 "D_NCOLS": "15600",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "22.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path10",
    //                 "AL_SH_PATH": "path11",
    //                 "AL_QL_PATH": "path12",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106280537361_ORT_3917261105.XML"
    //             },
    //             {
    //                 "id": 7,
    //                 "DATACODE": "AB112233",
    //                 "DATANAME": "DS_PHR1B_202106290537361_FR1_PX_E077N12_1123_01160",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008915",
    //                 "CL_ORDNA": "klm",
    //                 "CL_PROJNA": "klm",
    //                 "CL_PURPOSE": "klm",
    //                 "CL_ADDRESS1": "yza",
    //                 "CL_ADDRESS2": "bcd",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "29-06-2021",
    //                 "IMG_DT_RNG": "klm",
    //                 "DLOCA_CY": "klm",
    //                 "DLOCA_ST": "klm",
    //                 "DLOCA_DT": "klm",
    //                 "DLOCA_LOCA": "klm",
    //                 "DAREA": "70.1234",
    //                 "DSIZE": "1.6 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106290537361_ORT_3917261106.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "9",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31000",
    //                 "D_NCOLS": "15800",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "21.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path13",
    //                 "AL_SH_PATH": "path14",
    //                 "AL_QL_PATH": "path15",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106290537361_ORT_3917261106.XML"
    //             },
    //             {
    //                 "id": 8,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008916",
    //                 "CL_ORDNA": "hij",
    //                 "CL_PROJNA": "hij",
    //                 "CL_PURPOSE": "hij",
    //                 "CL_ADDRESS1": "efg",
    //                 "CL_ADDRESS2": "hij",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "30-06-2021",
    //                 "IMG_DT_RNG": "hij",
    //                 "DLOCA_CY": "hij",
    //                 "DLOCA_ST": "hij",
    //                 "DLOCA_DT": "hij",
    //                 "DLOCA_LOCA": "hij",
    //                 "DAREA": "75.1234",
    //                 "DSIZE": "1.7 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106300537361_ORT_3917261107.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "10",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31500",
    //                 "D_NCOLS": "16000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "20.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path16",
    //                 "AL_SH_PATH": "path17",
    //                 "AL_QL_PATH": "path18",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106300537361_ORT_3917261107.XML"
    //             },
    //             {
    //                 "id": 9,
    //                 "DATACODE": "AB334455",
    //                 "DATANAME": "DS_PHR1B_202107010537361_FR1_PX_E077N12_1123_01162",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008917",
    //                 "CL_ORDNA": "efg",
    //                 "CL_PROJNA": "efg",
    //                 "CL_PURPOSE": "efg",
    //                 "CL_ADDRESS1": "klm",
    //                 "CL_ADDRESS2": "nop",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "01-07-2021",
    //                 "IMG_DT_RNG": "efg",
    //                 "DLOCA_CY": "efg",
    //                 "DLOCA_ST": "efg",
    //                 "DLOCA_DT": "efg",
    //                 "DLOCA_LOCA": "efg",
    //                 "DAREA": "80.1234",
    //                 "DSIZE": "1.8 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107010537361_ORT_3917261108.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "11",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32000",
    //                 "D_NCOLS": "16200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "19.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path19",
    //                 "AL_SH_PATH": "path20",
    //                 "AL_QL_PATH": "path21",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107010537361_ORT_3917261108.XML"
    //             },
    //             {
    //                 "id": 10,
    //                 "DATACODE": "AB445566",
    //                 "DATANAME": "DS_PHR1B_202107020537361_FR1_PX_E077N12_1123_01163",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008918",
    //                 "CL_ORDNA": "ghi",
    //                 "CL_PROJNA": "ghi",
    //                 "CL_PURPOSE": "ghi",
    //                 "CL_ADDRESS1": "qrs",
    //                 "CL_ADDRESS2": "tuv",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "02-07-2021",
    //                 "IMG_DT_RNG": "ghi",
    //                 "DLOCA_CY": "ghi",
    //                 "DLOCA_ST": "ghi",
    //                 "DLOCA_DT": "ghi",
    //                 "DLOCA_LOCA": "ghi",
    //                 "DAREA": "85.1234",
    //                 "DSIZE": "1.9 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107020537361_ORT_3917261109.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "12",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32500",
    //                 "D_NCOLS": "16400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "18.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path22",
    //                 "AL_SH_PATH": "path23",
    //                 "AL_QL_PATH": "path24",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107020537361_ORT_3917261109.XML"
    //             }
    //         ]
    //     },
    //     {
    //         "name": "Table 3",
    //         "columns": [
    //             { "header": "id", "accessor": "id" },
    //             { "header": "DATACODE", "accessor": "DATACODE" },
    //             { "header": "DATANAME", "accessor": "DATANAME" },
    //             { "header": "COMP_NA", "accessor": "COMP_NA" },
    //             { "header": "SATT_NA", "accessor": "SATT_NA" },
    //             { "header": "CL_REF", "accessor": "CL_REF" },
    //             { "header": "CL_ORDNA", "accessor": "CL_ORDNA" },
    //             { "header": "CL_PROJNA", "accessor": "CL_PROJNA" },
    //             { "header": "CL_PURPOSE", "accessor": "CL_PURPOSE" },
    //             { "header": "CL_ADDRESS1", "accessor": "CL_ADDRESS1" },
    //             { "header": "CL_ADDRESS2", "accessor": "CL_ADDRESS2" },
    //             { "header": "SEN_NAME", "accessor": "SEN_NAME" },
    //             { "header": "IMG_DATYPE", "accessor": "IMG_DATYPE" },
    //             { "header": "IMG_DAPROC", "accessor": "IMG_DAPROC" },
    //             { "header": "IMG_DATE", "accessor": "IMG_DATE" },
    //             { "header": "IMG_DT_RNG", "accessor": "IMG_DT_RNG" },
    //             { "header": "DLOCA_CY", "accessor": "DLOCA_CY" },
    //             { "header": "DLOCA_ST", "accessor": "DLOCA_ST" },
    //             { "header": "DLOCA_DT", "accessor": "DLOCA_DT" },
    //             { "header": "DLOCA_LOCA", "accessor": "DLOCA_LOCA" },
    //             { "header": "DAREA", "accessor": "DAREA" },
    //             { "header": "DSIZE", "accessor": "DSIZE" },
    //             { "header": "DQLNAME", "accessor": "DQLNAME" },
    //             { "header": "DFORMAT", "accessor": "DFORMAT" },
    //             { "header": "DCLOUD", "accessor": "DCLOUD" },
    //             { "header": "DSNOW", "accessor": "DSNOW" },
    //             { "header": "D_AQ_BITS", "accessor": "D_AQ_BITS" },
    //             { "header": "D_PR_BITS", "accessor": "D_PR_BITS" },
    //             { "header": "DPRJ_TABLE", "accessor": "DPRJ_TABLE" },
    //             { "header": "DPRJ_NAME", "accessor": "DPRJ_NAME" },
    //             { "header": "D_NROWS", "accessor": "D_NROWS" },
    //             { "header": "D_NCOLS", "accessor": "D_NCOLS" },
    //             { "header": "D_NBANDS", "accessor": "D_NBANDS" },
    //             { "header": "D_NTILES", "accessor": "D_NTILES" },
    //             { "header": "D_TYPE", "accessor": "D_TYPE" },
    //             { "header": "D_NBITS", "accessor": "D_NBITS" },
    //             { "header": "D_SIGN", "accessor": "D_SIGN" },
    //             { "header": "D_IN_ANGL", "accessor": "D_IN_ANGL" },
    //             { "header": "D_GSD_AXT", "accessor": "D_GSD_AXT" },
    //             { "header": "D_GSD_ALT", "accessor": "D_GSD_ALT" },
    //             { "header": "D_PIXELX", "accessor": "D_PIXELX" },
    //             { "header": "D_PIXELY", "accessor": "D_PIXELY" },
    //             { "header": "AL_DA_PATH", "accessor": "AL_DA_PATH" },
    //             { "header": "AL_SH_PATH", "accessor": "AL_SH_PATH" },
    //             { "header": "AL_QL_PATH", "accessor": "AL_QL_PATH" },
    //             { "header": "XML_FILE", "accessor": "XML_FILE" }
    //         ],
    //         "data": [
    //             {
    //                 "id": 1,
    //                 "DATACODE": "AB823728",
    //                 "DATANAME": "DS_PHR1B_201903230537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008910",
    //                 "CL_ORDNA": "gfg",
    //                 "CL_PROJNA": "gdg",
    //                 "CL_PURPOSE": "fgdg",
    //                 "CL_ADDRESS1": "dgg",
    //                 "CL_ADDRESS2": "dfgg",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "23-03-2019",
    //                 "IMG_DT_RNG": "ggf",
    //                 "DLOCA_CY": "dgd",
    //                 "DLOCA_ST": "dfdg",
    //                 "DLOCA_DT": "dfgg",
    //                 "DLOCA_LOCA": "fg",
    //                 "DAREA": "69.5517",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_201903230538130_ORT_3917261101.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "0",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29372",
    //                 "D_NCOLS": "15407",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "26.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "dfgdg",
    //                 "AL_SH_PATH": "dg",
    //                 "AL_QL_PATH": "fgdg",
    //                 "XML_FILE": "DIM_PHR1B_PMS_201903230538130_ORT_3917261101.XML"
    //             },
    //             {
    //                 "id": 2,
    //                 "DATACODE": "AB340502",
    //                 "DATANAME": "PNEO3_202308040551179_PMS-FS_ORT",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PNEO",
    //                 "CL_REF": "A9-AOI",
    //                 "CL_ORDNA": "sadad",
    //                 "CL_PROJNA": "adasd",
    //                 "CL_PURPOSE": "adad",
    //                 "CL_ADDRESS1": "asdasd",
    //                 "CL_ADDRESS2": "asdasd",
    //                 "SEN_NAME": "PNEO 3",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS-FS",
    //                 "IMG_DATE": "04-08-2023",
    //                 "IMG_DT_RNG": "asdad",
    //                 "DLOCA_CY": "sdad",
    //                 "DLOCA_ST": "adad",
    //                 "DLOCA_DT": "asda",
    //                 "DLOCA_LOCA": "sdad",
    //                 "DAREA": "103.8210153",
    //                 "DSIZE": "8.8 GB",
    //                 "DQLNAME": "PREVIEW_PNEO3_202308040551179_PMS-FS_ORT_PWOI_000116673_1_2_F_1.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "64.74064722",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "16",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32644",
    //                 "D_NROWS": "34608",
    //                 "D_NCOLS": "34776",
    //                 "D_NBANDS": "6",
    //                 "D_NTILES": "4",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "31.67836468",
    //                 "D_GSD_AXT": "0.40711993",
    //                 "D_GSD_ALT": "0.343409747",
    //                 "D_PIXELX": "0.3",
    //                 "D_PIXELY": "0.3",
    //                 "AL_DA_PATH": "adad",
    //                 "AL_SH_PATH": "ads",
    //                 "AL_QL_PATH": "adsad",
    //                 "XML_FILE": "DIM_PNEO3_PMS-FS_202308040551179_ORTHO_PWOI_000116673_1_2_F_1.XML"
    //             },
    //             {
    //                 "id": 3,
    //                 "DATACODE": "AB123456",
    //                 "DATANAME": "DS_PHR1B_202106250537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008911",
    //                 "CL_ORDNA": "xyz",
    //                 "CL_PROJNA": "xyz",
    //                 "CL_PURPOSE": "xyz",
    //                 "CL_ADDRESS1": "abc",
    //                 "CL_ADDRESS2": "def",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "25-06-2021",
    //                 "IMG_DT_RNG": "xyz",
    //                 "DLOCA_CY": "xyz",
    //                 "DLOCA_ST": "xyz",
    //                 "DLOCA_DT": "xyz",
    //                 "DLOCA_LOCA": "xyz",
    //                 "DAREA": "50.1234",
    //                 "DSIZE": "1.2 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106250537361_ORT_3917261102.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "5",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29000",
    //                 "D_NCOLS": "15000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "25.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path1",
    //                 "AL_SH_PATH": "path2",
    //                 "AL_QL_PATH": "path3",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106250537361_ORT_3917261102.XML"
    //             },
    //             {
    //                 "id": 4,
    //                 "DATACODE": "AB654321",
    //                 "DATANAME": "DS_PHR1B_202106260537361_FR1_PX_E077N12_1123_01157",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008912",
    //                 "CL_ORDNA": "uvw",
    //                 "CL_PROJNA": "uvw",
    //                 "CL_PURPOSE": "uvw",
    //                 "CL_ADDRESS1": "ghi",
    //                 "CL_ADDRESS2": "jkl",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "26-06-2021",
    //                 "IMG_DT_RNG": "uvw",
    //                 "DLOCA_CY": "uvw",
    //                 "DLOCA_ST": "uvw",
    //                 "DLOCA_DT": "uvw",
    //                 "DLOCA_LOCA": "uvw",
    //                 "DAREA": "55.1234",
    //                 "DSIZE": "1.3 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106260537361_ORT_3917261103.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "6",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29500",
    //                 "D_NCOLS": "15200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "24.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path4",
    //                 "AL_SH_PATH": "path5",
    //                 "AL_QL_PATH": "path6",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106260537361_ORT_3917261103.XML"
    //             },
    //             {
    //                 "id": 5,
    //                 "DATACODE": "AB765432",
    //                 "DATANAME": "DS_PHR1B_202106270537361_FR1_PX_E077N12_1123_01158",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008913",
    //                 "CL_ORDNA": "rst",
    //                 "CL_PROJNA": "rst",
    //                 "CL_PURPOSE": "rst",
    //                 "CL_ADDRESS1": "mno",
    //                 "CL_ADDRESS2": "pqr",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "27-06-2021",
    //                 "IMG_DT_RNG": "rst",
    //                 "DLOCA_CY": "rst",
    //                 "DLOCA_ST": "rst",
    //                 "DLOCA_DT": "rst",
    //                 "DLOCA_LOCA": "rst",
    //                 "DAREA": "60.1234",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106270537361_ORT_3917261104.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "7",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30000",
    //                 "D_NCOLS": "15400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "23.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path7",
    //                 "AL_SH_PATH": "path8",
    //                 "AL_QL_PATH": "path9",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106270537361_ORT_3917261104.XML"
    //             },
    //             {
    //                 "id": 6,
    //                 "DATACODE": "AB987654",
    //                 "DATANAME": "DS_PHR1B_202106280537361_FR1_PX_E077N12_1123_01159",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008914",
    //                 "CL_ORDNA": "opq",
    //                 "CL_PROJNA": "opq",
    //                 "CL_PURPOSE": "opq",
    //                 "CL_ADDRESS1": "stu",
    //                 "CL_ADDRESS2": "vwx",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "28-06-2021",
    //                 "IMG_DT_RNG": "opq",
    //                 "DLOCA_CY": "opq",
    //                 "DLOCA_ST": "opq",
    //                 "DLOCA_DT": "opq",
    //                 "DLOCA_LOCA": "opq",
    //                 "DAREA": "65.1234",
    //                 "DSIZE": "1.5 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106280537361_ORT_3917261105.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "8",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30500",
    //                 "D_NCOLS": "15600",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "22.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path10",
    //                 "AL_SH_PATH": "path11",
    //                 "AL_QL_PATH": "path12",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106280537361_ORT_3917261105.XML"
    //             },
    //             {
    //                 "id": 7,
    //                 "DATACODE": "AB112233",
    //                 "DATANAME": "DS_PHR1B_202106290537361_FR1_PX_E077N12_1123_01160",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008915",
    //                 "CL_ORDNA": "klm",
    //                 "CL_PROJNA": "klm",
    //                 "CL_PURPOSE": "klm",
    //                 "CL_ADDRESS1": "yza",
    //                 "CL_ADDRESS2": "bcd",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "29-06-2021",
    //                 "IMG_DT_RNG": "klm",
    //                 "DLOCA_CY": "klm",
    //                 "DLOCA_ST": "klm",
    //                 "DLOCA_DT": "klm",
    //                 "DLOCA_LOCA": "klm",
    //                 "DAREA": "70.1234",
    //                 "DSIZE": "1.6 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106290537361_ORT_3917261106.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "9",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31000",
    //                 "D_NCOLS": "15800",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "21.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path13",
    //                 "AL_SH_PATH": "path14",
    //                 "AL_QL_PATH": "path15",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106290537361_ORT_3917261106.XML"
    //             },
    //             {
    //                 "id": 8,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008916",
    //                 "CL_ORDNA": "hij",
    //                 "CL_PROJNA": "hij",
    //                 "CL_PURPOSE": "hij",
    //                 "CL_ADDRESS1": "efg",
    //                 "CL_ADDRESS2": "hij",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "30-06-2021",
    //                 "IMG_DT_RNG": "hij",
    //                 "DLOCA_CY": "hij",
    //                 "DLOCA_ST": "hij",
    //                 "DLOCA_DT": "hij",
    //                 "DLOCA_LOCA": "hij",
    //                 "DAREA": "75.1234",
    //                 "DSIZE": "1.7 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106300537361_ORT_3917261107.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "10",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31500",
    //                 "D_NCOLS": "16000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "20.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path16",
    //                 "AL_SH_PATH": "path17",
    //                 "AL_QL_PATH": "path18",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106300537361_ORT_3917261107.XML"
    //             },
    //             {
    //                 "id": 9,
    //                 "DATACODE": "AB334455",
    //                 "DATANAME": "DS_PHR1B_202107010537361_FR1_PX_E077N12_1123_01162",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008917",
    //                 "CL_ORDNA": "efg",
    //                 "CL_PROJNA": "efg",
    //                 "CL_PURPOSE": "efg",
    //                 "CL_ADDRESS1": "klm",
    //                 "CL_ADDRESS2": "nop",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "01-07-2021",
    //                 "IMG_DT_RNG": "efg",
    //                 "DLOCA_CY": "efg",
    //                 "DLOCA_ST": "efg",
    //                 "DLOCA_DT": "efg",
    //                 "DLOCA_LOCA": "efg",
    //                 "DAREA": "80.1234",
    //                 "DSIZE": "1.8 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107010537361_ORT_3917261108.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "11",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32000",
    //                 "D_NCOLS": "16200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "19.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path19",
    //                 "AL_SH_PATH": "path20",
    //                 "AL_QL_PATH": "path21",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107010537361_ORT_3917261108.XML"
    //             },
    //             {
    //                 "id": 10,
    //                 "DATACODE": "AB445566",
    //                 "DATANAME": "DS_PHR1B_202107020537361_FR1_PX_E077N12_1123_01163",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008918",
    //                 "CL_ORDNA": "ghi",
    //                 "CL_PROJNA": "ghi",
    //                 "CL_PURPOSE": "ghi",
    //                 "CL_ADDRESS1": "qrs",
    //                 "CL_ADDRESS2": "tuv",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "02-07-2021",
    //                 "IMG_DT_RNG": "ghi",
    //                 "DLOCA_CY": "ghi",
    //                 "DLOCA_ST": "ghi",
    //                 "DLOCA_DT": "ghi",
    //                 "DLOCA_LOCA": "ghi",
    //                 "DAREA": "85.1234",
    //                 "DSIZE": "1.9 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107020537361_ORT_3917261109.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "12",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32500",
    //                 "D_NCOLS": "16400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "18.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path22",
    //                 "AL_SH_PATH": "path23",
    //                 "AL_QL_PATH": "path24",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107020537361_ORT_3917261109.XML"
    //             },
    //             {
    //                 "id": 11,
    //                 "DATACODE": "AB334455",
    //                 "DATANAME": "DS_PHR1B_202107010537361_FR1_PX_E077N12_1123_01162",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008917",
    //                 "CL_ORDNA": "efg",
    //                 "CL_PROJNA": "efg",
    //                 "CL_PURPOSE": "efg",
    //                 "CL_ADDRESS1": "klm",
    //                 "CL_ADDRESS2": "nop",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "01-07-2021",
    //                 "IMG_DT_RNG": "efg",
    //                 "DLOCA_CY": "efg",
    //                 "DLOCA_ST": "efg",
    //                 "DLOCA_DT": "efg",
    //                 "DLOCA_LOCA": "efg",
    //                 "DAREA": "80.1234",
    //                 "DSIZE": "1.8 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107010537361_ORT_3917261108.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "11",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32000",
    //                 "D_NCOLS": "16200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "19.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path19",
    //                 "AL_SH_PATH": "path20",
    //                 "AL_QL_PATH": "path21",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107010537361_ORT_3917261108.XML"
    //             },
    //             {
    //                 "id": 12,
    //                 "DATACODE": "AB445566",
    //                 "DATANAME": "DS_PHR1B_202107020537361_FR1_PX_E077N12_1123_01163",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008918",
    //                 "CL_ORDNA": "ghi",
    //                 "CL_PROJNA": "ghi",
    //                 "CL_PURPOSE": "ghi",
    //                 "CL_ADDRESS1": "qrs",
    //                 "CL_ADDRESS2": "tuv",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "02-07-2021",
    //                 "IMG_DT_RNG": "ghi",
    //                 "DLOCA_CY": "ghi",
    //                 "DLOCA_ST": "ghi",
    //                 "DLOCA_DT": "ghi",
    //                 "DLOCA_LOCA": "ghi",
    //                 "DAREA": "85.1234",
    //                 "DSIZE": "1.9 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202107020537361_ORT_3917261109.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "12",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "32500",
    //                 "D_NCOLS": "16400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "18.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path22",
    //                 "AL_SH_PATH": "path23",
    //                 "AL_QL_PATH": "path24",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202107020537361_ORT_3917261109.XML"
    //             }
    //         ]
    //     },
    //     {
    //         "name": "Table 4",
    //         "columns": [
    //             { "header": "id", "accessor": "id" },
    //             { "header": "DATACODE", "accessor": "DATACODE" },
    //             { "header": "DATANAME", "accessor": "DATANAME" },
    //             { "header": "COMP_NA", "accessor": "COMP_NA" },
    //             { "header": "SATT_NA", "accessor": "SATT_NA" },
    //             { "header": "CL_REF", "accessor": "CL_REF" },
    //             { "header": "CL_ORDNA", "accessor": "CL_ORDNA" },
    //             { "header": "CL_PROJNA", "accessor": "CL_PROJNA" },
    //             { "header": "CL_PURPOSE", "accessor": "CL_PURPOSE" },
    //             { "header": "CL_ADDRESS1", "accessor": "CL_ADDRESS1" },
    //             { "header": "CL_ADDRESS2", "accessor": "CL_ADDRESS2" },
    //             { "header": "SEN_NAME", "accessor": "SEN_NAME" },
    //             { "header": "IMG_DATYPE", "accessor": "IMG_DATYPE" },
    //             { "header": "IMG_DAPROC", "accessor": "IMG_DAPROC" },
    //             { "header": "IMG_DATE", "accessor": "IMG_DATE" },
    //             { "header": "IMG_DT_RNG", "accessor": "IMG_DT_RNG" },
    //             { "header": "DLOCA_CY", "accessor": "DLOCA_CY" },
    //             { "header": "DLOCA_ST", "accessor": "DLOCA_ST" },
    //             { "header": "DLOCA_DT", "accessor": "DLOCA_DT" },
    //             { "header": "DLOCA_LOCA", "accessor": "DLOCA_LOCA" },
    //             { "header": "DAREA", "accessor": "DAREA" },
    //             { "header": "DSIZE", "accessor": "DSIZE" },
    //             { "header": "DQLNAME", "accessor": "DQLNAME" },
    //             { "header": "DFORMAT", "accessor": "DFORMAT" },
    //             { "header": "DCLOUD", "accessor": "DCLOUD" },
    //             { "header": "DSNOW", "accessor": "DSNOW" },
    //             { "header": "D_AQ_BITS", "accessor": "D_AQ_BITS" },
    //             { "header": "D_PR_BITS", "accessor": "D_PR_BITS" },
    //             { "header": "DPRJ_TABLE", "accessor": "DPRJ_TABLE" },
    //             { "header": "DPRJ_NAME", "accessor": "DPRJ_NAME" },
    //             { "header": "D_NROWS", "accessor": "D_NROWS" },
    //             { "header": "D_NCOLS", "accessor": "D_NCOLS" },
    //             { "header": "D_NBANDS", "accessor": "D_NBANDS" },
    //             { "header": "D_NTILES", "accessor": "D_NTILES" },
    //             { "header": "D_TYPE", "accessor": "D_TYPE" },
    //             { "header": "D_NBITS", "accessor": "D_NBITS" },
    //             { "header": "D_SIGN", "accessor": "D_SIGN" },
    //             { "header": "D_IN_ANGL", "accessor": "D_IN_ANGL" },
    //             { "header": "D_GSD_AXT", "accessor": "D_GSD_AXT" },
    //             { "header": "D_GSD_ALT", "accessor": "D_GSD_ALT" },
    //             { "header": "D_PIXELX", "accessor": "D_PIXELX" },
    //             { "header": "D_PIXELY", "accessor": "D_PIXELY" },
    //             { "header": "AL_DA_PATH", "accessor": "AL_DA_PATH" },
    //             { "header": "AL_SH_PATH", "accessor": "AL_SH_PATH" },
    //             { "header": "AL_QL_PATH", "accessor": "AL_QL_PATH" },
    //             { "header": "XML_FILE", "accessor": "XML_FILE" }
    //         ],
    //         "data": [
    //             {
    //                 "id": 1,
    //                 "DATACODE": "AB823728",
    //                 "DATANAME": "DS_PHR1B_201903230537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008910",
    //                 "CL_ORDNA": "gfg",
    //                 "CL_PROJNA": "gdg",
    //                 "CL_PURPOSE": "fgdg",
    //                 "CL_ADDRESS1": "dgg",
    //                 "CL_ADDRESS2": "dfgg",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "23-03-2019",
    //                 "IMG_DT_RNG": "ggf",
    //                 "DLOCA_CY": "dgd",
    //                 "DLOCA_ST": "dfdg",
    //                 "DLOCA_DT": "dfgg",
    //                 "DLOCA_LOCA": "fg",
    //                 "DAREA": "69.5517",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_201903230538130_ORT_3917261101.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "0",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29372",
    //                 "D_NCOLS": "15407",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "26.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "dfgdg",
    //                 "AL_SH_PATH": "dg",
    //                 "AL_QL_PATH": "fgdg",
    //                 "XML_FILE": "DIM_PHR1B_PMS_201903230538130_ORT_3917261101.XML"
    //             },
    //             {
    //                 "id": 2,
    //                 "DATACODE": "AB340502",
    //                 "DATANAME": "PNEO3_202308040551179_PMS-FS_ORT",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PNEO",
    //                 "CL_REF": "A9-AOI",
    //                 "CL_ORDNA": "sadad",
    //                 "CL_PROJNA": "adasd",
    //                 "CL_PURPOSE": "adad",
    //                 "CL_ADDRESS1": "asdasd",
    //                 "CL_ADDRESS2": "asdasd",
    //                 "SEN_NAME": "PNEO 3",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS-FS",
    //                 "IMG_DATE": "04-08-2023",
    //                 "IMG_DT_RNG": "asdad",
    //                 "DLOCA_CY": "sdad",
    //                 "DLOCA_ST": "adad",
    //                 "DLOCA_DT": "asda",
    //                 "DLOCA_LOCA": "sdad",
    //                 "DAREA": "103.8210153",
    //                 "DSIZE": "8.8 GB",
    //                 "DQLNAME": "PREVIEW_PNEO3_202308040551179_PMS-FS_ORT_PWOI_000116673_1_2_F_1.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "64.74064722",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "16",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32644",
    //                 "D_NROWS": "34608",
    //                 "D_NCOLS": "34776",
    //                 "D_NBANDS": "6",
    //                 "D_NTILES": "4",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "31.67836468",
    //                 "D_GSD_AXT": "0.40711993",
    //                 "D_GSD_ALT": "0.343409747",
    //                 "D_PIXELX": "0.3",
    //                 "D_PIXELY": "0.3",
    //                 "AL_DA_PATH": "adad",
    //                 "AL_SH_PATH": "ads",
    //                 "AL_QL_PATH": "adsad",
    //                 "XML_FILE": "DIM_PNEO3_PMS-FS_202308040551179_ORTHO_PWOI_000116673_1_2_F_1.XML"
    //             },
    //             {
    //                 "id": 3,
    //                 "DATACODE": "AB123456",
    //                 "DATANAME": "DS_PHR1B_202106250537361_FR1_PX_E077N12_1123_01156",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008911",
    //                 "CL_ORDNA": "xyz",
    //                 "CL_PROJNA": "xyz",
    //                 "CL_PURPOSE": "xyz",
    //                 "CL_ADDRESS1": "abc",
    //                 "CL_ADDRESS2": "def",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "25-06-2021",
    //                 "IMG_DT_RNG": "xyz",
    //                 "DLOCA_CY": "xyz",
    //                 "DLOCA_ST": "xyz",
    //                 "DLOCA_DT": "xyz",
    //                 "DLOCA_LOCA": "xyz",
    //                 "DAREA": "50.1234",
    //                 "DSIZE": "1.2 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106250537361_ORT_3917261102.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "5",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29000",
    //                 "D_NCOLS": "15000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "25.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path1",
    //                 "AL_SH_PATH": "path2",
    //                 "AL_QL_PATH": "path3",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106250537361_ORT_3917261102.XML"
    //             },
    //             {
    //                 "id": 4,
    //                 "DATACODE": "AB654321",
    //                 "DATANAME": "DS_PHR1B_202106260537361_FR1_PX_E077N12_1123_01157",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008912",
    //                 "CL_ORDNA": "uvw",
    //                 "CL_PROJNA": "uvw",
    //                 "CL_PURPOSE": "uvw",
    //                 "CL_ADDRESS1": "ghi",
    //                 "CL_ADDRESS2": "jkl",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "26-06-2021",
    //                 "IMG_DT_RNG": "uvw",
    //                 "DLOCA_CY": "uvw",
    //                 "DLOCA_ST": "uvw",
    //                 "DLOCA_DT": "uvw",
    //                 "DLOCA_LOCA": "uvw",
    //                 "DAREA": "55.1234",
    //                 "DSIZE": "1.3 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106260537361_ORT_3917261103.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "6",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "29500",
    //                 "D_NCOLS": "15200",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "24.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path4",
    //                 "AL_SH_PATH": "path5",
    //                 "AL_QL_PATH": "path6",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106260537361_ORT_3917261103.XML"
    //             },
    //             {
    //                 "id": 5,
    //                 "DATACODE": "AB765432",
    //                 "DATANAME": "DS_PHR1B_202106270537361_FR1_PX_E077N12_1123_01158",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008913",
    //                 "CL_ORDNA": "rst",
    //                 "CL_PROJNA": "rst",
    //                 "CL_PURPOSE": "rst",
    //                 "CL_ADDRESS1": "mno",
    //                 "CL_ADDRESS2": "pqr",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "27-06-2021",
    //                 "IMG_DT_RNG": "rst",
    //                 "DLOCA_CY": "rst",
    //                 "DLOCA_ST": "rst",
    //                 "DLOCA_DT": "rst",
    //                 "DLOCA_LOCA": "rst",
    //                 "DAREA": "60.1234",
    //                 "DSIZE": "1.4 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106270537361_ORT_3917261104.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "7",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30000",
    //                 "D_NCOLS": "15400",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "23.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path7",
    //                 "AL_SH_PATH": "path8",
    //                 "AL_QL_PATH": "path9",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106270537361_ORT_3917261104.XML"
    //             },
    //             {
    //                 "id": 6,
    //                 "DATACODE": "AB987654",
    //                 "DATANAME": "DS_PHR1B_202106280537361_FR1_PX_E077N12_1123_01159",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008914",
    //                 "CL_ORDNA": "opq",
    //                 "CL_PROJNA": "opq",
    //                 "CL_PURPOSE": "opq",
    //                 "CL_ADDRESS1": "stu",
    //                 "CL_ADDRESS2": "vwx",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "28-06-2021",
    //                 "IMG_DT_RNG": "opq",
    //                 "DLOCA_CY": "opq",
    //                 "DLOCA_ST": "opq",
    //                 "DLOCA_DT": "opq",
    //                 "DLOCA_LOCA": "opq",
    //                 "DAREA": "65.1234",
    //                 "DSIZE": "1.5 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106280537361_ORT_3917261105.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "8",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "30500",
    //                 "D_NCOLS": "15600",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "22.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path10",
    //                 "AL_SH_PATH": "path11",
    //                 "AL_QL_PATH": "path12",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106280537361_ORT_3917261105.XML"
    //             },
    //             {
    //                 "id": 7,
    //                 "DATACODE": "AB112233",
    //                 "DATANAME": "DS_PHR1B_202106290537361_FR1_PX_E077N12_1123_01160",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008915",
    //                 "CL_ORDNA": "klm",
    //                 "CL_PROJNA": "klm",
    //                 "CL_PURPOSE": "klm",
    //                 "CL_ADDRESS1": "yza",
    //                 "CL_ADDRESS2": "bcd",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "29-06-2021",
    //                 "IMG_DT_RNG": "klm",
    //                 "DLOCA_CY": "klm",
    //                 "DLOCA_ST": "klm",
    //                 "DLOCA_DT": "klm",
    //                 "DLOCA_LOCA": "klm",
    //                 "DAREA": "70.1234",
    //                 "DSIZE": "1.6 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106290537361_ORT_3917261106.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "9",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31000",
    //                 "D_NCOLS": "15800",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "21.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path13",
    //                 "AL_SH_PATH": "path14",
    //                 "AL_QL_PATH": "path15",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106290537361_ORT_3917261106.XML"
    //             },
    //             {
    //                 "id": 8,
    //                 "DATACODE": "AB223344",
    //                 "DATANAME": "DS_PHR1B_202106300537361_FR1_PX_E077N12_1123_01161",
    //                 "COMP_NA": "AIRBUS DS GEO",
    //                 "SATT_NA": "PLEIADES",
    //                 "CL_REF": "SO19008916",
    //                 "CL_ORDNA": "hij",
    //                 "CL_PROJNA": "hij",
    //                 "CL_PURPOSE": "hij",
    //                 "CL_ADDRESS1": "efg",
    //                 "CL_ADDRESS2": "hij",
    //                 "SEN_NAME": "PHR 1B",
    //                 "IMG_DATYPE": "ORTHO",
    //                 "IMG_DAPROC": "PMS",
    //                 "IMG_DATE": "30-06-2021",
    //                 "IMG_DT_RNG": "hij",
    //                 "DLOCA_CY": "hij",
    //                 "DLOCA_ST": "hij",
    //                 "DLOCA_DT": "hij",
    //                 "DLOCA_LOCA": "hij",
    //                 "DAREA": "75.1234",
    //                 "DSIZE": "1.7 GB",
    //                 "DQLNAME": "PREVIEW_PHR1B_PMS_202106300537361_ORT_3917261107.JPG",
    //                 "DFORMAT": "image/tiff",
    //                 "DCLOUD": "10",
    //                 "DSNOW": "0",
    //                 "D_AQ_BITS": "12",
    //                 "D_PR_BITS": "12",
    //                 "DPRJ_TABLE": "EPSG",
    //                 "DPRJ_NAME": "32643",
    //                 "D_NROWS": "31500",
    //                 "D_NCOLS": "16000",
    //                 "D_NBANDS": "4",
    //                 "D_NTILES": "2",
    //                 "D_TYPE": "INTEGER",
    //                 "D_NBITS": "16",
    //                 "D_SIGN": "UNSIGNED",
    //                 "D_IN_ANGL": "20.65226319",
    //                 "D_GSD_AXT": "0.784700042",
    //                 "D_GSD_ALT": "0.839099306",
    //                 "D_PIXELX": "0.5",
    //                 "D_PIXELY": "0.5",
    //                 "AL_DA_PATH": "path16",
    //                 "AL_SH_PATH": "path17",
    //                 "AL_QL_PATH": "path18",
    //                 "XML_FILE": "DIM_PHR1B_PMS_202106300537361_ORT_3917261107.XML"
    //             }
    //         ]
    //     }
    // ]



    return (
        <>
            <div>
                <div className="Tble-Header">
                    <div className="Tbl-Menu-bar">
                        <Dropdown className="Drop-down-font-size">
                            <Dropdown.Toggle variant="" id="dropdown-basic">
                                <i className="fa-solid fa-bars"></i>
                            </Dropdown.Toggle>
                            <Dropdown.Menu>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {FindAndReplace} alt="FindAndReplace"/></span>Find and Replace</Dropdown.Item>
                                <Dropdown.Divider />
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {SelectByAttribute} alt="SelectByAttribute"/></span>Select by Attribute</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {SwitchSelection} alt="SwitchSelection"/></span>Switch Selection</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {ClearSelection} alt="ClearSelection"/></span>Clear Selection</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {SelectAll} alt="Select All"/></span>Select All</Dropdown.Item>
                                <Dropdown.Divider />

                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {AddFields} alt="Add Fields"/></span>Add Fields</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {ViewFields} alt="View Fields"/></span>View Fields</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {TurnAllFieldsON} alt="Turn All Fields ON"/></span>Turn All Fields ON</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {ShowFieldsAliases} alt="ShowFieldsAliases"/></span>Show Fields Aliases</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {CalculateFields} alt="Calculate Fields"/></span>Calculate Fields</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {""} alt=""/></span>Restore Field order</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {""} alt=""/></span>Restore Default Field Width</Dropdown.Item>
                                <Dropdown.Divider />

                                {/* Submenu: Arrange Tables */}
                                <div
                                    className="dropdown-item dropdown-submenu"
                                    onMouseEnter={() => toggleSubmenu('arrangeTables', true)}
                                    onMouseLeave={() => toggleSubmenu('arrangeTables', false)}
                                >
                                     <span className="SVG-icon-size"><img src = {ArrangeTables} alt="Arrange Tables"/></span><span>Arrange Tables</span> <i class="fa-solid fa-caret-down"></i>
                                    {visibleSubmenus.arrangeTables && (
                                        <div className="dropdown-menu">
                                            <Dropdown.Item href="#/submenu-1"><span className="SVG-icon-size"><img src = {HorizontalTabGroup} alt="Horizontal Tab Group"/></span>Horizontal Tab Group</Dropdown.Item>
                                            <Dropdown.Item href="#/submenu-2"><span className="SVG-icon-size"><img src = {VerticalTabGroup} alt="Vertical Tab Group"/></span>Vertical Tab Group</Dropdown.Item>
                                        </div>
                                    )}
                                </div>

                                {/* Submenu: Join and Relate */}
                                <div
                                    className="dropdown-item dropdown-submenu"
                                    onMouseEnter={() => toggleSubmenu('joinAndRelate', true)}
                                    onMouseLeave={() => toggleSubmenu('joinAndRelate', false)}
                                >
                                    <span className="SVG-icon-size"><img src = {JoinandRelate} alt="Join and Relate"/></span><span>Join and Relate</span> <i class="fa-solid fa-caret-down"></i>
                                    {visibleSubmenus.joinAndRelate && (
                                        <div className="dropdown-menu">
                                            <Dropdown.Item href="#/submenu-1"><span className="SVG-icon-size"><img src = {JoinTable} alt="Join Table"/></span> Join Table</Dropdown.Item>
                                            <Dropdown.Item href="#/submenu-2"><span className="SVG-icon-size"><img src = {Removejoin} alt="Remove join"/></span> Remove join(s)</Dropdown.Item>
                                        </div>
                                    )}
                                </div>

                                {/* Submenu: Related Tables */}
                                <div
                                    className="dropdown-item dropdown-submenu"
                                    onMouseEnter={() => toggleSubmenu('relatedTables', true)}
                                    onMouseLeave={() => toggleSubmenu('relatedTables', false)}
                                >
                                    <span className="SVG-icon-size"><img src = {RelatedTables} alt="RelatedTables"/></span><span>Related Tables</span> <i class="fa-solid fa-caret-down"></i>
                                    {visibleSubmenus.relatedTables && (
                                        <div className="dropdown-menu">
                                            <Dropdown.Item href="#/submenu-1"><span className="SVG-icon-size"><img src = {Relate} alt="Relate"/></span>Relate</Dropdown.Item>
                                            <Dropdown.Item href="#/submenu-2"><span className="SVG-icon-size"><img src = {RemoveRelate} alt="Remove Relate"/></span>Remove Relate(s)</Dropdown.Item>
                                        </div>
                                    )}
                                </div>
                                <Dropdown.Divider />
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {""} alt=""/></span>Print</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {""} alt=""/></span>Report</Dropdown.Item>
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {Export} alt="Export"/></span>Export</Dropdown.Item>
                                <Dropdown.Divider />
                                <Dropdown.Item href=""><span className="SVG-icon-size"><img src = {""} alt=""/></span>Appearance</Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>
                    </div>
                </div>


                <div className="Table-Body-div">

                    {/* <div>
                        {
                            TablePointvalues?.features?.length > 0 ? (
                                TablePointvalues.features.map((item, index) => {
                                    console.log("Item Points Table:", item);
                                    // Render your content here
                                    return <div key={index}> 
                                    
                                    {item.geometry.type}
                                    {item.properties.AUD_GRP}
                                    {item.properties.AUD_GRP}
                                    {item.properties.AUD_ERRP}
                                    
                                    </div>;
                                })
                            ) : (
                                <p>No data available</p>
                            )
                        }
                    </div> */}

                    <GeopicxTables tables={tablesss} />

                </div>

                
            </div>
        </>
    )
}

export default TableContentsComp
